### ISSUE TITLE
Issue with Colorbox and Knockout Validation

### ISSUE THREAD

**Issue by grofit** [Knockout-Contrib/Knockout-Validation#159]
Hey,

Have been using Knockout Validation for a while without issue, but I have recently come across something strange... which *MAY* not be an issue and just me being an idiot, but I am out of ideas so thought I would post on here incase you can forsee the problem straight away.

I basically have an overridden default binding behaviour with knockout, so anything which has validation extensions will raise an event whenever the isValid observable changes... much like so:

```javascript
var originalKoValueInit = ko.bindingHandlers.value.init;
ko.bindingHandlers.value.init = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
    originalKoValueInit(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext);
	
    var observable = valueAccessor();
    if (!ko.validation.utils.isValidatable(observable)) { return; }

    var $element = $(element);
    observable.isValid.subscribe(function (valid) {
		if (!valid) 
		{ /* Do something for failure */ }
		else 
		{ /* Do something for success */ }
    });
}
```

This works perfectly everywhere on the site,  apart from this ONE bit which happens to be used within a dialog box.

Now the dialog box is created using ColorBox, and is hosted as an inline element (so it should move the DOM element into the colorbox for the duration of the dialog existing, then will spit it back out into where it originally was in the DOM once its done). So the dialog content is always in the DOM but is hidden until required. Now the problem is not as clear cut as saying *it doesn't work* as thats not 100% correct.

The behaviour I am seeing is that the IsValid subscription is not being notified of validation errors, so if I was having minLength: 5 in there, I could put 3 characters in, lose focus and it would not raise the event. HOWEVER! The bizarre thing is that if I put in some valid data, I find that it then DOES raise the event, and any subsequent validation errors are then raised correctly... 

I imagine its to do with the DOM elements being moved around in the DOM tree is somehow causing the bindings to mess up somehow, but I dont get how it fixes itself once when something passes validation... So does anything spring to mind as to what could cause this...

As its not a *Simple* problem I haven't had time to make an jsfiddle for it, but will try to do so tomorrow and post up if I get time.

**Comment by crissdev** [comment]
Updated fiddle http://jsfiddle.net/3deu83hr/

**Comment by grofit** [comment]
Yes sure, I do not even remember raising it.
