### ISSUE TITLE
Disable and enable validation does not work

### ISSUE THREAD

**Issue by AndersMalmgren** [Knockout-Contrib/Knockout-Validation#171]
Please see this closed issue
https://github.com/ericmbarnard/Knockout-Validation/issues/101

The user story for this was thrown back in the backlog so I never got to test this, but now that story re emerged again so i got to test it out. 

It works to disable the validation if using .extend({ validatable: false });
To disable on a specific validation rule level does not work
However to reenable validation does not work, I didnt find a way to reopen a issue so i open a new one, hope its ok..

Thanks

**Comment by rameshinnoblitz** [comment]
perfect solution for me. thank a lot steve
