### ISSUE TITLE
ASP.NET MVC bundle issue with .min file

### ISSUE THREAD

**Issue by brianchance** [Knockout-Contrib/Knockout-Validation#172]
Ran into an issue when using the .min version with ASP.NET MVC bundles. For the most part, everything works correctly. Where I ran into trouble was using the submit binding handler to check .isValid before allowing form submission. When using the .min version in a bundle, the form validated, showed errors but still submitted.

I used the .min version outside the bundle and it works correctly. 
I also used the debug file in the bundle and it works correctly.

I think the issue is that the bundler re-minifies the file, which is generally works. So I tried another minifier (http://jscompress.com/), included it in the bundle and it works correctly.

Not sure if grunt.js is to aggressive? Anyway, just wanted to post the issue here in case others ran into it. What I ended up doing was keeping just the normal file (without the .debug extension, just .js). This way the normal file is sent when not bundling, and it is only minified once when it is bundled.

Brian

**Comment by scantyaspnet-mvc-5264** [comment]
@ericmbarnard https://vstoaccountable580.github.io/autodesk-forge/
