### ISSUE TITLE
Knockout Validation & Proper way to clear controls

### ISSUE THREAD

**Issue by jmogera** [Knockout-Contrib/Knockout-Validation#210]
This issue that I am having is that the validation happens right away after I call:

this.SomeProperty(null);

The intention is clear out a textbox when you press "add", have the textbox empty until you have to validate it.

ko.validation.configure({
        insertMessages: false,
        decorateElement: true,
        errorElementClass: 'error'
    });

FirstName: ko.observable().extend({
            required: true
        }),

addItem: function () {
            if (!viewModel.isValid()) {
                viewModel.errors.showAllMessages();
                return false;
            } else {
                //DO SOMETHING
                this.SomeCollection.push(newInterviewee);
                this.FirstName(null);
                }
        },

<div>
<label>First Name</label>
<input data-bind="value: FirstName, validationElement: FirstName, valueUpdate: 'keyup'" class="input" type="text">
</div>

<div>
<div>
<input data-bind="click: addItem" class="button" type="button">
</div>

**Comment by jonathancounihan-sage** [comment]
Hi,

If you use [deferred updates](http://knockoutjs.com/documentation/deferred-updates.html) for knockout (available from 3.4), then this method of resetting the validation does not work.

I have created a fiddle to demo the issue: https://jsfiddle.net/crazyJ/qjub2buL/2/

Any suggestions on how to handle this?

Thanks

**Comment by McKabue** [comment]
@jonathancounihan-sage i am also experiencing the same issue... please notify me when you find a solution...

**Comment by slaneyrw** [comment]
The issue is that setting the field value does not notify immediate execute subscriptions, so setting isModified to false manually is being overridden when the subscriptions to eventually run.

As a workaround, you need to force notification before setting isModified

    viewModel.name("");
    viewModel.email("");
    ko.tasks.runEarly();
    viewModel.name.isModified(false);
    viewModel.email.isModified(false);
