### ISSUE TITLE
ko.bindingHandlers.validationCore.init doesn't work

### ISSUE THREAD

**Issue by jmogera** [Knockout-Contrib/Knockout-Validation#230]
I am trying to a custom binding to input as  datepicker: 
CODE HERE: http://sdrv.ms/Xc5HZw

I have the following code in place but the validation doesn't highlight the control when its invalid:

<pre>   
ko.bindingHandlers.datepicker = {
        init: function (element, valueAccessor, allBindingsAccessor) {
           // code here

          ko.bindingHandlers.validationCore.init(element, valueAccessor, allBindingsAccessor);

        },
        update: function (element, valueAccessor) {
				
           // code here
        }
    };
</pre>

**Comment by crissdev** [comment]
@jmogera The link to the code is no longer valid. Please close this issue or add a comment to it. Thanks.
