### ISSUE TITLE
Consecutive rules failing keep the first rule message

### ISSUE THREAD

**Issue by knockoutuser** [Knockout-Contrib/Knockout-Validation#231]
I'm using the 

    ko.validation.group(model, { deep: true, observable: true }) 

method to create myself an observer that collects error messages form one textbox field.

I have an issue when using more rules, like `required` + `max`, each with it's own message: `Required message` and `Too big message` respectively. 

If I leave the field empty I get the `Required message` because the `required` rule is triggered and fails.

If I then insert a very large value into the field the `required` rule isn't triggered anymore but the `max` rule is. But the message collected by my ko.validation.group observer remains as `Required message` instead of being  `Too big message`.

I've done some debugging and I believe it's this piece of code that is the cause:

    function validateSync(observable, rule, ctx) {
            //Execute the validator and see if its valid
            if (!rule.validator(observable(), ctx.params === undefined ? true : ctx.params)) { //     default param is true, eg. required = true
    
                //not valid, so format the error message and stick it in the 'error' variable
                observable.error = ko.validation.formatMessage(ctx.message || rule.message, ctx.params);
                observable.__valid__(false);
                return false;
            } else {
                return true;
            }
        } 

If the `max` validator fails it sets the `observable.__valid__(false)` but this triggers no change because the `required` rule failed previously and set it to false. Old value false, new value false no subscribers are notified => the message does not change.

At least that's my understanding, correct me if I'm wrong.

Is it possible to have the `errors` array populated correctly?

**Comment by crissdev** [comment]
Closing this issue because at that time `observable.error` was not observable, thus causing this problem.
