### ISSUE TITLE
validation.group does not update when a field with multiple validators goes from one error state to another

### ISSUE THREAD

**Issue by NerdENerd** [Knockout-Contrib/Knockout-Validation#244]
If a field on the model has multiple validators the validation.group is not always up to date with the current error state of the model. For the group to update one of the fields must change state between valid and invalid, it does not get updated if a field moves from one invalid state to another.

In this fiddle http://jsfiddle.net/e4LHV/2/ just hit the save button and the UL bound to the group will have the correct error. Then enter text into amount field, the message next to the amount field will have the correct message but the group will not have updated. To get the group to update you need to trigger one of the fields to change state to valid. Enter the description and then the group will have the correct message for the amount.

See this post on stackoverflow.
http://stackoverflow.com/questions/15329076/ko-validation-group-not-always-up-to-date-with-displayed-errors

**Comment by crissdev** [comment]
Already fixed by #248.
