### ISSUE TITLE
isModified for group

### ISSUE THREAD

**Issue by fastfasterfastest** [Knockout-Contrib/Knockout-Validation#250]
I have a ko.validation.group in my viewmodel.  
I would like to find out if any of validatable observables in the group has been modified, however, I don't think the group exposes a isModified method (but I may be wrong...).

Is there a convenient way for me to implement isModified for the group?

**Comment by crissdev** [comment]
This functionality can be achieved with utility methods available on ko.validation.group return value #500.

```js
var group = ko.validation.group(vm);
var isModified = !!group.find(function(observable) {
   return ko.validation.utils.isValidatable(observable) && observable.isModified();
});
```
