### ISSUE TITLE
jsFiddle link in ReadMe.md has an invalid external ref to KnockoutJS

### ISSUE THREAD

**Issue by adamskt** [Knockout-Contrib/Knockout-Validation#251]
The [jsFiddle link](http://jsfiddle.net/ericbarnard/KHFn8/) in the ReadMe.md references the latest KnockoutJS at https://raw.github.com/SteveSanderson/knockout/master/build/output/knockout-latest.debug.js which is no longer valid.  The build output for KnockoutJS is no longer available in GitHub source as of [this checkin](https://github.com/SteveSanderson/knockout/commit/253c74d8d076e6d9d46ac839fe958c2060f4dc62#build/output).

**Comment by crissdev** [comment]
jsFiddle in README.md http://jsfiddle.net/KHFn8/2971/ still needs to be updated:
- use Knockout-Validation from [cdn](https://cdnjs.com/libraries/knockout-validation)
- use more recent version of [Knockout](https://cdnjs.com/libraries/knockout) (e.g. 3.2.0) and update example to include `textInput` binding
