### ISSUE TITLE
Attempting to use with require.js causes "ko is not defined"

### ISSUE THREAD

**Issue by colin-young** [Knockout-Contrib/Knockout-Validation#259]
I'm configuring require like so:

```
paths: {
    blockui: 'jquery.blockUI',
    jquery: 'jquery-1.9.1.min',
    jqueryui: 'jquery-ui-1.10.1.min',
    knockout: 'knockout-2.2.1',
    komapping: 'knockout.mapping-latest',
    validation: 'knockout.validation',
    token: 'jquery.tokeninput'
}
```

But when I later use the validation:

define(['jquery', 'knockout', 'komapping', 'Views/add-report-wizard-model', 'token', 'validation'], function ($, ko, mapping, ViewModel, token, validation) { ... });

It fails with "ko is not defined." Is there an example somewhere of how I need to reference knockout.validation with require.js?

**Comment by DenEwout** [comment]
Hi, I'm experiencing some difficulties regarding this. Any update on a fix without using the workaround above?

**Comment by crissdev** [comment]
@DenEwout Please ensure you're using the correct version (at least 2.0.0) and your requiresjs configuration is properly set up. If you still think there's an issue in the library then reply with an example on [plnk](http://plnkr.co/).
