### ISSUE TITLE
Rules are added multiple times when options.parseInputAttributes and options.writeInputAttributes are both set to true.

### ISSUE THREAD

**Issue by benpriebe** [Knockout-Contrib/Knockout-Validation#277]
When the parseInputAttributes and writeInputAttributes options are set to true; the writeInputAttributes occurs first; then the parseInputAttributes comes along after and says hey, there's some input attributes that i should go create rules for - even though we already have the rule.

**See fiddle for verification:**
http://jsfiddle.net/t2y5F/

**Suggestion:**

Modify addRule() function to check the rule isn't there already. Something like:
```javascript
 addRule: function(observable, rule) {
                if (!utils.isValidatable(observable))
                    observable.extend({ validatable: true });

                var hasRule;
                ko.utils.arrayForEach(observable.rules(), function(arrRule) {
                    if (arrRule.name == rule.name) {
                        hasRule = true;
                        return;
                    }
                });

                if (!hasRule) {
                    //push a Rule Context to the observables local array of Rule Contexts
                    observable.rules.push(rule);
                }
                return observable;
            },
```

**Comment by crissdev** [comment]
The rule will not be added if it already exists. Tis will apply only to rules that have a name.

```js

var obsv = ko.observable(1).extend({ min: 10 });

// obsv.rules().length is 1

obsv.extend({ min: 20 }); // The rule will NOT be added because it already exists

// obsv.rules().length is still 1
```

For the upcoming releases we might consider #441 - preferably avoiding breaking changes.

**Comment by Helen1987** [comment]
Hm, actually this change is breaking change for me. I need a possibility to set a rule with the same name at least twice in some cases (although rule name is the same, parameters are different). I even created a bug #618. Can be this issue fixed in a different way?
