### ISSUE TITLE
Pattern with "i" modifier (case-insensitive matching) does not work

### ISSUE THREAD

**Issue by joncortez** [Knockout-Contrib/Knockout-Validation#291]
If I specify a regex with an "i" modifier for case-insensitive matching, the validation fails even with a valid value.

Example:
pattern - /email@company.com/i

test values:
email@company.com - passes
Email@company.com - fails
Email@Company.Com - fails

**Comment by madmox** [comment]
Actually this does not work when HTML5 native validation is enabled. The `pattern` attribute added to the HTML input tag is case sensitive, so a form submission triggers an error even when knockout validation passes.

See: https://jsfiddle.net/vwpwwsou/1/
When you type `A` in the textbox, you can't submit the form, although the regex specifies case insensitivity.
