### ISSUE TITLE
Number validation matches string

### ISSUE THREAD

**Issue by mokkabonna** [Knockout-Contrib/Knockout-Validation#326]
IMO the number validation should check that the observable is a number, not that it is a string that happens to be a number.

I can understand that this is convenient as you can just bind it with the value binding to a text input and the binding updates the observable with a string, and all are happy.

However IMO then you should rather use bindings that do that conversion for you. (shameless plug: http://mokkabonna.github.io/knockout.bindingHandlers.number/)

Also the check for , (thousands separator) does not belong here. It should be the bindings job to sanitize the users input and represent that in the model as a number.

Same could be says for other validators I imagine. I see the date does the same, it checks if the value in the observable is something that can be made into a date, not that it is a date object..

**Comment by crissdev** [comment]
Closing this issue since the current behaviour won't change.
