### ISSUE TITLE
Custom rules always show errors as soon as they are invalid regardless of configuration

### ISSUE THREAD

**Issue by gjharris** [Knockout-Contrib/Knockout-Validation#366]
My model is structured like this:

viewModel {
   observableArrayOfObjects([
      observableProperty;
      observableProperty;
      observableArrayOfObjects([])
   ]).extend(custom rule)
}

Both observable arrays contain objects that themselves have a bunch of ko.validation extended rules and a validation group.

My config is: 

ko.validation.configure({
    insertMessages: false,
    decorateElement: true,
    errorElementClass: 'has-error',
    group: {deep: true}
});

In my view, I have a some divs that contain all the error messages for each object if 'isAnyMessageShown()' is true for that object:

These all work perfectly. The error divs do not display until I call showAllMessages on the error group of the object.

But my custom rule for some reason is always showing it's error as soon as it equates to true,  before I ever call showAllMessages. Is this intended functionality? Am I perhaps missing something key?

**Comment by fknop** [comment]
Hi,

I'm bringing back this after 2 years, I have the same issue, what's the solution afterall ?
