### ISSUE TITLE
Remote Validation Rules and group.validationErrors().length

### ISSUE THREAD

**Issue by mariusfilipowski** [Knockout-Contrib/Knockout-Validation#380]
I really like the support of async rules via ajax. 
I am facing now a problem, when I use them.

I have a custom submit-button on my page that should only work, when all validation rules are met (validationErrors().length === 0). This works perfectly with normal rules.
But when I have a remote rules with multiple fields, that at first are correct but when I've entered invalid input, the remote validation starts. 
In the meantime - for some seconds - I am able to trigger my submit button since the remote validation rules are still running and no validation errors are in that array.

What is the best way to solve this?
My idea: It would be nice when the validationGroup would also provide a check for the isValidating()-Observable of all containing observables. 

Thanks for helping...

**Comment by crissdev** [comment]
The grouping feature now gives access to validatables through some Array methods #449. This means you can write things like:

```js

var group = ko.validation.group({ /*properties*/ });

var isValidating = !!result.find(function(observable) {
    return !!ko.unwrap(observable.isValidating);
});

```
