### ISSUE TITLE
Issues with library not working with knockout 3.* 

### ISSUE THREAD

**Issue by roscopeeco** [Knockout-Contrib/Knockout-Validation#434]
Hello
It would be great if you gys could fix this issue for version 2.0 of the Knockout-Validation. I've been looking through the issues history It has been reported a number of times as an issue and i myself have had to stop using the library becuase i've encountered the same issues (e.g. grouping:{ deep:true}, raising a too much recursion error) in a project.

It was a shame to have to stop using an otherwise invaluable library but if it don't work it can't be used!!

Thanks
Ross

**Comment by crissdev** [comment]
Duplicate #413
