### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by AndersMalmgren** [Knockout-Contrib/Knockout-Validation#444]
The nuget package is out of date

**Comment by crissdev** [comment]
NuGet package will be updated when 2.0 version is released.

**Comment by amaitland** [comment]
Any chance of releasing a `-pre` nuget package? Happy to create a PR with the relevant `nuspec` changes.

**Comment by crissdev** [comment]
The v2 will be released in a few days - so a `pre-release` will not take place. You may download the library from the `Dist` directory. Release notes available here #469

**Comment by amaitland** [comment]
@crissdev Greatly appreciated, thanks!

(Offer still stands if you need help with the `nuget` packages)

**Comment by crissdev** [comment]
Thanks @amaitland No worries about the NuGet package - it's already updated but not yet published. The `nuspec` in the repository is something to vanish with upcoming commits.

**Comment by amaitland** [comment]
@crissdev Thanks for responding so quickly :+1:

**Comment by crissdev** [comment]
Nuget package has been updated.
