### ISSUE TITLE
Issue with deep Group traversal over observable array

### ISSUE THREAD

**Issue by slaneyrw** [Knockout-Contrib/Knockout-Validation#468]
I have an issue with the value of the errors from a validation group created for an ObservableArray.
1.  Create an empty observable array.
2.  Create a validation group for the array.  The array is now made validatable, but it has isValid, error AND errors properties.
3.  Push a validatable observable into the array.  If the observable is not valid then both the array and group have 1 error in their respective errors property.
4.  Push another validable observable into the array.    If this observable is also not valid then I get 3 errors in the error group -> [null, {first element's error}, {second element's error}].

The null error appears to be coming from the observable array, but it's reading the error property, not the errors property.  I would have expected only 2 errors reported, one from each of the elements from the array.

This Jasmine test shows the issue

```
it('Group traverses observable array with live option', function() {
    var items = ko.observableArray();
    var errors = ko.validation.group(items, {deep: true, live: true});
    expect(errors().length).toEqual(0);

    items.push(ko.observable().extend({required: {message: 'first error'}}));

    expect(errors().length).toEqual(1);
    expect(errors()[0]).toEqual('first error');

    items.push(ko.observable().extend({required: {message: 'second error'}}));

    expect(errors().length).toEqual(2);           // This expectation fails, length === 3
    expect(errors()[0]).toEqual('first error');   // This expectation fails, [0] === null
    expect(errors()[1]).toEqual('second error');  // This expectation fails, [1] === 'first error'
});
```

**Comment by lookforit** [comment]
@slaneyrw 
@crissdev 
I met with the same isuue,and currently i'm using 2.0.3.
The detail is :
When push a new item in the observable array, the validation keeps silent(`errors()().length=0`) even setting the setting the new item's field invalid.
Untill you trigger the older items validation manually（eg，change one of them to be invalid）,the whole validation will update correctly now.
Pls check.
