### ISSUE TITLE
Inconsistent Required rule behavior for arrays

### ISSUE THREAD

**Issue by lostincomputer** [Knockout-Contrib/Knockout-Validation#505]
Required rule handles arrays inconsistently. If the observable array is [""], it is considered as empty. However, if the array is ["",""] or ["a"], it is considered as not empty.

I suggest to possible solutions:
1. Mirror .net required behavior since I guess that most developers use Knockout with .Net framework. 
The .net required validator flags the value as empty if it is null or empty string.

2. Value is empty if null, undefined, empty string, empty object or empty array.
This

**Comment by lostincomputer** [comment]
sorry for the typos and formatting errors

**Comment by crissdev** [comment]
The `required` rule is not for arrays. The reason why it works for `[""]` is because when converted to string it's an empty string. For your use case I presume you need a custom rule.

**Comment by lostincomputer** [comment]
Why not just make the required rule "empty if value is null, undefined or empty string"? Is it for compatibility?

**Comment by crissdev** [comment]
That's actually how it works. http://jsfiddle.net/ba6n96w7/

**Comment by lostincomputer** [comment]
sorry for not making my previous message clear. I meant only. Value is empty Only if null, undefined or empty string. [], [""], ["a"] will not be treated as empty.

**Comment by crissdev** [comment]
I can't see any reason those values should be handled by `required` rule. In my oppinion that validation should be covered by a custom rule.

**Comment by crissdev** [comment]
@lostincomputer can you provide a real use case for this? It would provide better insight to this issue.

**Comment by lostincomputer** [comment]
No issue. I was just nitpicking.
