### ISSUE TITLE
Localization loading randomly breaks when using requirejs

### ISSUE THREAD

**Issue by davhdavh** [Knockout-Contrib/Knockout-Validation#509]
It is not currently possible to configure a general requirejs dependency rule that covers all current and future localizations, and since the localization only tells requirejs it depends on knockout, the loading randomly breaks.

**Comment by crissdev** [comment]
Can you provide more information about your use case? Consider usin http://plnkr.co/ to create an example - to better explain your issue.

**Comment by ViceIce** [comment]
I found the error!

The localization files should require knockout.validaion not knockout.

That's why requirejs sometimes initialize the localization before knockout.validation.

Regards,
Michael

**Comment by crissdev** [comment]
Thanks Michael.

Great to see the module ID you sugget is `knockout.validation` and not with a hyphen. This is something that will be implemented in a future version of the library.

**Comment by crissdev** [comment]
@ViceIce do you want to submit a PR for this?

**Comment by ViceIce** [comment]
If you want, i can do this.

**Comment by crissdev** [comment]
Sure, go ahead. Thanks.

**Comment by ViceIce** [comment]
Ok, give me some minutes. :-)

**Comment by crissdev** [comment]
Reopening this issue because some localization files were not refactored.

**Comment by ViceIce** [comment]
Which files?

**Comment by ViceIce** [comment]
Oh. I see it. eg:  `localization/pl-PL.js#L6`

I missed the the globals. I will check this

**Comment by crissdev** [comment]
Thanks @ViceIce for your interest on this. It seems there's more to fix than some AMD loading - somehow I missed that localization messages are not exported for nodejs when I first worked on it.

**Comment by ViceIce** [comment]
Ok, haven't used it with node. Maybe some tests are required.

Anything i can do?

**Comment by crissdev** [comment]
No worrries, I already started on this - there's only the fix for nodejs left. But thanks.

**Comment by ViceIce** [comment]
Ok, no problem. :+1:
