### ISSUE TITLE
isValidatable code

### ISSUE THREAD

**Issue by damianof** [Knockout-Contrib/Knockout-Validation#525]
isValidatable: function (o) {
			return !!(o && o.rules && o.isValid && o.isModified);
		}

If isModified and isValid are observables, shouldnt this code be changed to:

                isValidatable: function (o) {
			return !!(o && o.rules && (o.isValid && o.isValid()) && (o.isModified && o.isModified()));
		}

or am i missing something?

**Comment by crissdev** [comment]
Th

**Comment by damianof** [comment]
So setting isModified(false) on a field that is disabled might not be enough to disable validation?

**Comment by crissdev** [comment]
To disable validation you can either use [conditional validation](https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Conditional-Validation-with-onlyIf-parameter) or remove it completely with the `validatable` extender `observable.extend({validatable: false})`. Setting `isModified` to false will just hide the error message.

**Comment by damianof** [comment]
we are on an older version of ko, there is no onlyIf. Unfortunately this is a production app and can't just upgrade.

**Comment by crissdev** [comment]
`onlyIf` is available since `1.0.2` so you must be using a very old version. You should still be able to use the `validatable` extender to remove the validation for the field. If that's not an option for you then consider asking this question on stackoverflow.

Consider checking the release notes for version `2.0.0` and try to upgrade. It will be more likely to receive help for ongoing versions.

**Comment by damianof** [comment]
First, thank you for your prompt responses and help. Yes, this is some technical debt we have inherited here and it will require eventually to upgrade. We have been looking in what the  best path would be to eventually move to the latest version of knockout, but there are other implications. Meanwhile to fix a couple of bugs we have I'll try to implement a workaround that adds something similar to the onlyIf. Thank you again.

**Comment by crissdev** [comment]
No problemo Damiano. Good luck and leave a comment here if there's something I can help you with.
