### ISSUE TITLE
Not re-evaluation when html5 element gets hidden

### ISSUE THREAD

**Issue by Bjolja** [Knockout-Contrib/Knockout-Validation#532]
I'm using validation on html5 elements and it is working fine as long as they are visible. I have the following code and a button being disabled when error-count exeeds 0.

Here are the following scenarios:
1. ShouldBindElement is false, error count is 0
2. ShouldBindElement is true, the input has invalid date, error count is 1
3. ShouldBindElement is true, input has valid date, error count is 0
4. ShouldBindElement i false, then set to true, then back to false, the error coutnt is still 1 because the input was invalid when visible, and the error count remains.

Is this is bug or am i missing something? In my world, the error count should go back to 0 since the element is no longer being validated?

     <div data-bind="if: ShouldBindElement, visible: ShouldBindElement">
                <input data-bind="date : DateOfEvent" required="required" type="date">
     </div>

**Comment by crissdev** [comment]
The visibility of the element bound to the observable does not affect validation. I think you need something like [Conditional Validation](https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Conditional-Validation-with-onlyIf-parameter).

**Comment by Bjolja** [comment]
Using conditional validation requires me to add code to my view model and that would make the logic behind it a lot more complex. Is there any way to force re-evaluation?

(I simplified the code when putting it here. My real code is more complex)

**Comment by crissdev** [comment]
Well, that's how the ViewModel thing works. The view simply displays information from the ViewModel. Since your observables are not valid, it doesn't really matter if the bound controls are visible or not. If you were to create some unit tests for the ViewModel then you would not be forced to have HTML behind it.

Take the following unit test - written using QUnit:

```js
QUnit.test('observable is not valid', function(assert) {
    var obs = ko.observable('').extend({required: true});

    assert.equal(obs.isValid(), false);
    assert.equal(obs.error(), 'This field is required.');
});
```

As you can see, there's no HTML here, still, the validation works.

**Comment by Bjolja** [comment]
Hi,
I'm well aware of this, but I have a wizard with different steps and different validation criterias for each wizard step and therefore it was very handy to have inline validation of the observables of elements instead of having extensive validation logic in the viewmodel for each wizard step. In worst case I'll create a viewmodel for each wizard step but that is a work I'd rather not do because it will be harder to maintain in the long run since it is about 25 steps.

But again, Is there any way to force re-evaluation? 
I might be able to go around the problem force the code to re-evaluate all bound observables again? Since it is inside the if-statement it will not be bound. It is not the visibility I'm after, it is the fact that the observable no longer will be bound thanks to the if-statement.

**Comment by crissdev** [comment]
You can re-validate your observables by notifying the subscribers with `obs.valueHasMutated()` or `obs.notifySubscribers`. You may also choose to create a group for each step, but this will require some coding.

**Comment by Bjolja** [comment]
I created a bindinghandler to clear all errors and force validation to re create all rules. It works for now, but does it affect performance much?
    ko.bindingHandlers.validatable = {
        init: function (element, valueAccessor, allBindings, vm, bindingContext) {
            ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
                valueAccessor().obs.valueHasMutated();
                valueAccessor().errors.clearAllErrors();
            });
        }
    }

**Comment by crissdev** [comment]
The performance depends on several factors. If you don't have too many bindings on the page you should be fine. You may also observe how it behaves when showing / hiding elements.

**Comment by Bjolja** [comment]
Awesome feedback. You are great crissdev!

**Comment by crissdev** [comment]
Thanks @Bjolja 
:+1:
