### ISSUE TITLE
localize method does not update existing bindings

### ISSUE THREAD

**Issue by errorx666** [Knockout-Contrib/Knockout-Validation#533]
I have a translation web service that provides localized strings.  It is asynchronous.

When I apply bindings, the original, untranslated messages show up, even after I call the `localize` method with new strings.

If I, e.g., enter text into a required field, and then remove it, I will see the localized message for that field, but the other required fields still show the original messaging.

Ideally, the messages for different validation rules should be observable values so updating them would propagate to existing messages.

**Comment by crissdev** [comment]
Duplicate #158
