### ISSUE TITLE
2.0.0-Pre

### ISSUE THREAD

**Issue by damiandennis** [Knockout-Contrib/Knockout-Validation#535]
NPM is still showing this version 2.0.0-Pre which does not seem to exist, I am not using NPM but another tool that uses npm and its throwing an error, any chance on avoiding deletion of tags or a way to fix it in NPM.

**Comment by crissdev** [comment]
###### npm info knockout.validation versions
```
[ '2.0.0-Pre',
  '2.0.0-pre.1',
  '2.0.0-pre.2',
  '2.0.0-pre.3',
  '2.0.0',
  '2.0.1',
  '2.0.2' ]
```
---
###### bower info knockout-validation
```
  - 2.0.2
  - 2.0.1
  - 2.0.0
  - 1.0.2
```

---
###### tags
```
  - v0.9
  - v1.0.2 
  - 2.0.0 
  - 2.0.1
  - 2.0.2
```

---
###### nuget
```
  - 1.0.0
  - 1.0.1
  - 2.0.0
  - 2.0.2
```

These are all the versions available through various packaging systems. 

* Unpublishing packages from npm is not recommended >> https://docs.npmjs.com/cli/unpublish
* Removing any tags would make some versions not available through Bower.
* Adding missing tags doesn't seem a good idea

You may want to inspect the output of your tool and submit an issue to their repo.

**Comment by damiandennis** [comment]
Ok thats fair enough, I worked it out using bower instead. I will submit a ticket to that tool to correct non existent tags from crashing the whole system.
