### ISSUE TITLE
Validation OK and validation required CSS classes

### ISSUE THREAD

**Issue by 79it** [Knockout-Contrib/Knockout-Validation#551]
To support a validation OK and required CSS class in a previous project I made some alterations to enable this functionality.

By having a validation OK class we can provide visual feedback that the field contains a valid value - e.g. green border or injecting a tick image into the field.

By having a validation required class we can provide visual feedback that the field is required - e.g. inserting * after the field label or injecting an asterisk image into the field.

I have forked the main project, would this be of interest to the main project?

Thanks

Chris

**Comment by crissdev** [comment]
Please check the example available in this SO thread http://stackoverflow.com/questions/12531489/knockout-validation-success-classes/12642364#12642364
Is this what you're trying to accomplish?

**Comment by 79it** [comment]
The idea of the stackoverflow post is what I'm after. Unfortunately the JSBin doesn't work but I definitely want this as the default behaviour.

Is duck punching the ko.bindingHandlers['validationElement'] handler possible? I'd rather not specify a completely new binding handler in case the core changes significantly breaking validation etc.

Once I figure out how to get grunt working on my computer and the code checked in perhaps you can check my fork to see if this something that could potentially get added to the core?

**Comment by crissdev** [comment]
1. I don't know why JSBin didn't work for you because I double checked it and it works as expected.
2. I believe it's possible to overwrite the `validationElement` binding handler as long as you do this before `applyBindings` / `applyBindingsWithValidation` call.
3, Once you push something into your fork just add a comment here and I'll check it out.

Apart from that I think this issue is a duplicate of #142. Am I correct?

**Comment by 79it** [comment]
It's similar but subtly different - issue #142 is concerned only with a success class. I want to add a required class too.

I have committed the changes and you can see the code here:
https://github.com/79it/Knockout-Validation/commit/b6511419fb4c7810ab74f8d002182a5651081afc

I need to work on a demo and will try and do that tomorrow.

**Comment by crissdev** [comment]
Thanks for your effort. Now I see what you are trying to accomplish. But this isn't just about the required rule - other builtin / custom rules should also benefit of such functionality. I'm very convinced such functionality will be present in the library sometime soon (2.x of 3.x) but in a different shape. Until then you may find useful the implementation available in PR #306.

---
Just in case you decide to go further in your project with the fork: In `validationElement` binding handler you assume the first rule is a `required` rule. This may fail if you define multiple rules on your observable and `required` rule is not the first.

**Comment by 79it** [comment]
I'm looking forward to this being implemented in a future release.

In the meantime I will continue with my fork and make the code more robust.

Thanks

Chris
