### ISSUE TITLE
ValidationElement binding don't add css class to a binded element.

### ISSUE THREAD

**Issue by it3xl** [Knockout-Contrib/Knockout-Validation#555]
Accordingly to "" from the page https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Validation-Bindings
the ValidationElement don't add the css class to the binded element.

http://jsfiddle.net/it3xl/tf5ojecd/

Help me tame my Bootstrap styling :)

**Comment by it3xl** [comment]
I copied the binding's name from the header of the article, not from sample there.
https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Validation-Bindings

Without typo all works fine.
ValidationElement -> validationElement.
V -> v.

**Comment by it3xl** [comment]
I have corrected first letters to lowercase here: https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Validation-Bindings
Sorry if I wrong.

**Comment by crissdev** [comment]
@it3xl No, it's okay. It actually avoids confusion. Thanks.
