### ISSUE TITLE
Validating Array of Dynamically Created Validatable Objects

### ISSUE THREAD

**Issue by PeakEmployee** [Knockout-Contrib/Knockout-Validation#558]
I'm new to this validation framework and am loving it so far. I have most of it working just fine. However, I'm having difficulties with successfully validating an observableArray of validatable objects. My biz rules state that I must have at least one HrAdmin and then for each, I need to validate the name and email. With the code I have thus far, when the page loads:
* I have no "HRAdmin" objects. If I click the "Go to Step 3" link, I get the appropriate error. Good so far.  
* However, if I then click the "Add Manager" link, and then click the "Go to Step 3" link without filling in required fields, validation isn't occurring. 
* If I change my code to always initialize the self.HrAdmins observableArray with one HRAdmin object, then when I click the "Go to Step 3" link without filling in required fields, validation DOES occur on that object. 

It seems like validation isn't being wired up correctly when I dynamically add a new HrAdmin object to the observableArray. What am I doing wrong???

This is what I have so far: (I've stripped out irrelevant code for the sake of brevity and still isn't working correctly) And here's a fiddle: http://jsfiddle.net/3b3o87dy/3/

    ko.validation.rules['minArrayLength'] = {
            validator: function (obj, params) {
                return obj.length >= params.minLength;
            },
            message: "Must have at least {0} {1}"
        };

    ko.validation.registerExtenders();

     function HRAdmin()
        {
            this.FirstName = ko.observable("").extend({ validatable: true, required: true, minLength: 1, maxLength: 50 });
            this.LastName = ko.observable("").extend({ validatable: true, required: true, minLength: 1, maxLength: 50 });
            this.Email = ko.observable("").extend({ validatable: true, required: true, minLength: 1, maxLength: 100, email: true });
        }

     var CompanySignUpModel = function () {
            // PROPERTIES
            var self = this;
          
            self.HrAdmins = ko.observableArray([]).extend({
                minArrayLength: {
                    params: { minLength: 1, objectType: "Account Manager" },
                    message: 'Must specify at least one Account Manager'
                }
        } );

            self.HrAdminsErrors = ko.validation.group(self.HrAdmins(), { deep: true });
                                          
            self.AddHrAdmin = function (data, event) {
                self.HrAdmins.push(new ko.observable(new HRAdmin()));
            };
                        
            self.GoToStep3 = function (data, event) {
                var isValid = true;
                if (self.HrAdminsErrors().length != 0) {
                    self.HrAdminsErrors.showAllMessages();
                    isValid = false;
                }

                if (!self.HrAdmins.isValid())
                {
                    self.HrAdmins.notifySubscribers();
                    isValid = false;
                }

                if (!isValid) return;

                $("#step-3").removeClass("disabled");
                ScrollTo("step-3");
            };
        };

        ko.applyBindings(new CompanySignUpModel());

    <div data-bind="foreach: HrAdmins">
       <input type="text" placeholder="First Name" data-bind="value: FirstName" />
       <input type="text" placeholder="Last Name" data-bind="value: LastName" />
       <input type="text" placeholder="Email Address" data-bind="value: Email" />
    </div>
    <p data-bind="validationMessage: HrAdmins" class="validationMessage"></p>
    <a href="#" data-bind="click: $root.AddHrAdmin">Add Manager</a>
    <a href="#" data-bind="click: $root.GoToStep3">Go to Step 3</a>

**Comment by crissdev** [comment]
@PeakEmployee If I did understand your use case correctly then the following explanation should clarify it.

```js
// Provide the observable (HrAdmins), not its value, to 
// have it included in the validatable list (see src/api.js#L57)
self.HrAdminsErrors = ko.validation.group(self.HrAdmins, {
    deep: true,
    live: true   // Watch the HrAdmins observable array for changes
});
```

1. Passing the `HrAdmins` to the `group` method will ensure that it will be added to the validatable list
2. Adding `live` option will ensure further changes of the `HrAdmins` array will be picked up and validation triggered for the new items

Updated example http://jsfiddle.net/3b3o87dy/6/

**Comment by PeakEmployee** [comment]
You understood perfectly crissdev! I actually just "fixed" my problem by executing the line `self.HrAdminsErrors = ko.validation.group(self.HrAdmins(), { deep: true });` again in the AddHrAdmin function, but it seemed extraneous to me. So the `live` option works much better!

Thanks a ton!
