### ISSUE TITLE
Need a complete but small validation code

### ISSUE THREAD

**Issue by tridip-bba** [Knockout-Contrib/Knockout-Validation#566]
HI,

I Need a complete but small validation code which will have html with data-bind attribute and knockout js code.

suppose i am showing login form where user has to put user id, password and country name from dropdown then how html would look like and js code too?

which file i need to include. for now i always include a jquery and knockout js file. if i need to use your validation library then tell me file name with path which i need to include in my page.

i need to show custom validation message for each input.
say for example 
----------------------
1) user Name Required
2) Password Required
2) Select your country
this way validation message should come. thanks

**Comment by crissdev** [comment]
@tridip-bba Your question could get more response on StackOverflow, for instance. The issue tracker is for problems / enhancements related to the library. 

Please check the [wiki](https://github.com/Knockout-Contrib/Knockout-Validation/wiki) for examples of how the library works.
