### ISSUE TITLE
Number validation doesn't work for decimals with leading zero

### ISSUE THREAD

**Issue by chainbridgetech** [Knockout-Contrib/Knockout-Validation#570]
The number validation returns false and the message  'Please enter a number.' when the observable value is '.5'. However, the validation works fine if the leading zero is added, '0.5'. I know that parseFloat correctly handles '.5', so I would think that the number validation should allow for a decimal without the leading zero.

**Comment by crissdev** [comment]
@chainbridgetech I couldn't reproduce your issue. Maybe you're using an old version of the library?

Working example: http://jsfiddle.net/2pq8faco/

**Comment by chainbridgetech** [comment]
I am in fact running an old version. Sorry for the waste of time.
