### ISSUE TITLE
Nuget Pacake

### ISSUE THREAD

**Issue by fallenidol** [Knockout-Contrib/Knockout-Validation#573]

**Comment by fallenidol** [comment]
Today I spent the best part of 2 hours trying to debug an issue. It turns out after much hair pulling that I was in fact not using the OFFICIAL nuget package but some other package claiming to be 3.0.0. This non-offical nuget package is old code and buggy. https://www.nuget.org/packages/KnockoutJS.Validation

You might consider contacting this person and ask them to delist the nuget package. Or maybe you could consider adding some more text to your own package to make it more obvious that yours is the official one.

**Comment by crissdev** [comment]
@fallenidol Thanks for reporting this. I will contact the owner of the package. Once this problem is sorted out I will close this issue.

**Comment by crissdev** [comment]
@fallenidol The aforementioned package has been unlisted. There's still one more duplicate https://www.nuget.org/packages/Knockout-Validation/ which should be unlisted soon - owner of the package has been contacted.
