### ISSUE TITLE
Validation on blur

### ISSUE THREAD

**Issue by adbre** [Knockout-Contrib/Knockout-Validation#580]
Using a older version of knockout.validation, the valueUpdate: "blur" binding works.
Here is a fiddle that works http://jsfiddle.net/29ucZ/10/ using Knockout 3.2 and knockout.validation 1.0.2.
But changing knockout.validation to 2.0.3 the fiddle no longer works (http://jsfiddle.net/29ucZ/11/)

**Comment by crissdev** [comment]
@adbre Starting with version 2.0 `ko.validation.configure` is now `ko.validation.init`. The error can be seen in the browser's console too.

Updated example http://jsfiddle.net/xwtaj7jp/

---
[Release notes for 2.0.0](https://github.com/Knockout-Contrib/Knockout-Validation/releases/tag/2.0.0)

**Comment by adbre** [comment]
Yea, sorry about that. Seems my issue in my actual solution was that the observable was initialized with an empty string, unlike the fiddle where it was left undefined.
When I was able to observe the same behavior in the fiddle after upgrading, I jumped to the conclusion too fast.

Thank you for your patience...

**Comment by crissdev** [comment]
No problem.
