### ISSUE TITLE
equal with message

### ISSUE THREAD

**Issue by divmgl** [Knockout-Contrib/Knockout-Validation#587]
Trying to set a message using the `equal` validator.

```javascript
ko.observable().extend({
  equal: {
    onlyIf: () => self.signingUp(),
    params: self.password(),
    message: 'Your passwords must match.'
  }
});
```

However, the validation always fails. I'm assuming it's because i'm not supposed to use `params`. What is the correct way of passing a value to the `equal` validator?

**Comment by crissdev** [comment]
Pass the observable instead.
Example here https://github.com/Knockout-Contrib/Knockout-Validation/wiki/User-Contributed-Rules#are-same
