### ISSUE TITLE
Visual expression as Formvalidation.io

### ISSUE THREAD

**Issue by theodorjohannesen** [Knockout-Contrib/Knockout-Validation#607]
Hi guys.

One of my favorite form validation frameworks are from formvalidation.io - visually it just works.
That framework is capable of evaluating everything, including ko.observables(), but only those outside loops.
As i created an master-detail, the detail could not be evaluated, but the master input fields where "evalu-able".
This extention grabs the evaluation on blur event - as I just have seen. And writes out some text, and stops the form from submitting.
In what direction should I move to, to enable Knockout-Validation to express the same visual evaluation of inputfields as formsvalidation.io ?

Thanks,
Theodor

**Comment by crissdev** [comment]
@theodorjohannesen I haven't used that validation framework so far and I have no knowledge of how that works. Please consider asking your question on stackoverflow (for instance). This issue tracker is only for bugs / features etc. related to the library itself.

Thanks.

-
https://github.com/Knockout-Contrib/Knockout-Validation/wiki
