### ISSUE TITLE
I have a simple doubt.

### ISSUE THREAD

**Issue by Hernandesjunio** [Knockout-Contrib/Knockout-Validation#617]
When I uses ko.validation.utils.isEmptyVal, only return true or undefined. I suggest returns false if not empty.

**Comment by crissdev** [comment]
@Hernandesjunio indeed, it should return false. Do you want to submit a PR to fix it? Thanks

**Comment by Hernandesjunio** [comment]
Also I identified with some changes as needed to zip code validation using several rules. Tomorrow I will make a contribution to these corrections.
