### ISSUE TITLE
Validation message is duplicated if validationMessage binding is applied

### ISSUE THREAD

**Issue by sheehana** [Knockout-Contrib/Knockout-Validation#665]
The validation message which is shown when a property contains invalid input is **duplicated** if another element has the validationMessage binding applied for that property.

See this JSFiddle for example: [Knockout Validation Message Issue](https://jsfiddle.net/sheehan95/7xpykabw/9/)

**Steps to Reproduce:**
1. Open the JSFiddle
2. Remove the "default" text in the input area
3. Hit the enter key / move focus away from the input field
4. The error message "This field is required." is shown twice

The following should be displayed:
![validation-message-issue](https://user-images.githubusercontent.com/12477410/53338413-845aca00-38fb-11e9-9935-99426f9834b7.PNG)

The validation message should only be shown **once** whether or not the validationMessage binding is applied. It should be shown in the element where I explicitly used the validationMessage binding. In the above JSFiddle example, only the element with the black background should be displayed.

**Comment by wmbeers** [comment]
Initialize ko-validation and set the insertMessages option to false to prevent the duplicate message from showing up.

`ko.validation.init({insertMessages: false});`

Example fiddle:

https://jsfiddle.net/wmbeers/9rj4dahg/1/

**Comment by sheehana** [comment]
Thanks for the speedy response! Seems I should have read the documentation more thoroughly...

I'm happy to close this issue. Sorry for the trouble!

**Comment by rameshinnoblitz** [comment]
include this in your viewmodel

// VALIDATION RULES
    ko.validation.init({
        registerExtenders: true,
        messagesOnModified: true,
        insertMessages: false,
        parseInputAttributes: true,
        messageTemplate: null,
        errorElementClass: 'input-error',
        errorClass: 'text-danger',
        decorateElementOnModified: true,
        decorateInputElement: true
    }, true);

    self.errors = ko.validation.group(this, { deep: true, observable: false });
