### ISSUE TITLE
please add side effect key in packages.json

### ISSUE THREAD

**Issue by gregveres** [Knockout-Contrib/Knockout-Validation#666]
I am finding that webpack 4 is not including the knockout.validation package in my bundle. After reading this page on [tree shaking](https://webpack.js.org/guides/tree-shaking/), I think it would be useful if the side effect key was added to the packages.json file so that webpack could know that there are side effects in the package. 

Thanks

**Comment by crissdev** [comment]
@gregveres Actually it's the other way around. 
See this example https://github.com/webpack/webpack/tree/master/examples/side-effects
