### ISSUE TITLE
TypesScript 3.5.1 & Knockout 3.5.0 & Validation no longer compiling

### ISSUE THREAD

**Issue by cosmoKenney** [Knockout-Contrib/Knockout-Validation#669]
I just upgraded a very large project to use the latest of all npm packages. The big problem I have is that we have hundreds of references to knockout validation (and mapping) but none of my code compiles anymore. 
The call to `ko.validation.init` won't compile -- compiler says validation does not exist on `ko`.
The call to `ko.extend` won't compile when using `obs.extend( { required: ...` -- object literal may only specify know properties.

I'm using @types for ko, mapping and validation. What do I need to do to get this project compiling again?

What sucks is I also have another typescript project to upgrade. It's smaller but still make extensive use of validation.

**Comment by cosmoKenney** [comment]
I'm pretty stuck here. I've been tweaking tsconfig.json and installing and uninstalling different npm packages for two full days. Do I just need to bite the bullet and globally change all `ko.validation` to `(<any>ko).validation` in my hundreds of source files?
How would I fix the issue with "requred":
```javascript
	self.WatchDesc = ko.observable( model.WatchDesc ).extend( {
		required: { message: 'Please enter at least 4 characters for the reference id.' },
		minLength: { params: 4, message: "Please enter at least 4 characters for the reference id." },
		maxlength: 30
	} );
```
I get an error message about that not being assignable to parameter of type `ObservableExtenderOptions`.

**Comment by cosmoKenney** [comment]
I'm closing this. It isn't fixed but I found a work-around.

**Comment by peters** [comment]
@cosmoKenney Would you be so kind to share your workaround? :)

**Comment by cosmoKenney** [comment]
@peters
It's been a long time since I've looked at this project so I'm not sure exactly how I fixed it. I do not have `@types` installed for any of the knockout related libraries. 
I added a knockout.d.ts with this:
```javascript
declare namespace ko
{
	interface Subscribable<T = any>
	{
		BoundElement: any; // custom
		ErrorMessageOrder: string; // custom
		isValid: import( "../node_modules/knockout/build/types/knockout" ).Observable<boolean>;
		error: string;
		isValidating: import( "../node_modules/knockout/build/types/knockout" ).Observable<boolean>;
		isModified: import( "../node_modules/knockout/build/types/knockout" ).Observable<boolean>;
	}
	//interface Observable<T = any>
	//{
	//}
	interface ObservableExtenderOptions
	{
		ErrorMessageOrder?: any;
		BoundElement?: any;
		Required?: boolean;
		DirtyChecker?: boolean;
		_isValidSubscription?: import( "../node_modules/knockout/build/types/knockout" ).Subscription;
		validation?: any;
	}
}
```

And in my source file I:
```javascript
import * as ko from 'knockout';
import 'knockout-mapping';
import 'knockout.validation';
```
Then where I use validation:
```javascript
// *** note the placement of <any>:
	self.WatchDesc = ko.observable( model.WatchDesc ).extend( (<any>{
		required: { message: 'Please enter at least 4 characters for the reference id.' },
		minLength: { params: 4, message: "Please enter at least 4 characters for the reference id." },
		maxlength: 30
	}) );
```
