### ISSUE TITLE
Can't use validation error messages with custom knockout bindings

### ISSUE THREAD

**Issue by damonsmith** [Knockout-Contrib/Knockout-Validation#69]
Hi, I note that knockout-validation adds it's own version of ko.bindingHandlers.value.init, so that when you bind a value it adds the error message template and binds that to the validation error and message.

We have some of our own custom bindings that are similar to value but do slightly different things, like only allow numbers or use jquery multiselectors.

I would really like it if knockout-validation worked for these bindings the same way that it works for the value binding. Or even if there was a simple method to call that would add the current validationMessageElement to my element without my binding having to know the intimate details of knockout validation.

Even just a function that said ko.validation.addValidationMessage(element, valueAccessor) would be handy.

Maybe I'm missing something and it does. But it doesn't seem to work for me and looking at the code, it only seems to be applied to value bindings.

I can work around this for now by manually creating the error message alongside each custom binding but that's a bit too error prone for my liking.

**Comment by jkober** [comment]
en html : autoComplete: { selected: oficina, options: "array de oficinas" }

        let settings = ko.utils.unwrapObservable(valueAccessor());
        let selectedOption = settings.selected;// << selected propiedad que existe en autocomplete 

        ko.bindingHandlers.validationCore.init(element, function(){return selectedOption;}, allBindingsAccessor);
