### ISSUE TITLE
RadioButtonList Validation

### ISSUE THREAD

**Issue by DarrenClark25** [Knockout-Contrib/Knockout-Validation#89]
have issue where radiobuttonlists are not validating

the radiobuttonlist is rendered at runtime and the required attribute is applied on the fly. 
i have set the deep: true as i would like to traverse all my full object graph and validate , dropdownlists seem to validate with no issues.

I can get the validation to kick in for radio buttons if i set extend on the observable in the viewmodel, but insertValidationMessage is not fired. The problem is i cannot use extend from code as my radio button lists are dynamically generated at runtime.

Anyone else experienced this problem?

http://jsfiddle.net/4TQ9j/11/

**Comment by crissdev** [comment]
Working example http://jsfiddle.net/xdu8bgbb/

Fixed by 7ae827d99a339b0ab94375ae0f59e6fdb0e86a8f
